# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master, next]
  pull_request:
    branches: ["*"]
  release:
    types: [created]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Install packages"
        run: bun install

      - name: "Format code"
        run: bun run format

      - name: "Build code"
        run: bun run build

      - name: "Test"
        run: bun run test

  publish-npm:
    name: "Publish: npm Registry"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: "https://registry.npmjs.org"

      - name: "Install packages"
        run: bun install

      - name: "Build code"
        run: bun run build

      - name: "Test"
        run: bun run test

      - name: "Publish to NPM"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish --access=public
